### ISSUE TITLE
ingress fails to deploy but reports success

### ISSUE THREAD

**Issue by dwradcliffe** [Shopify/kubernetes-deploy#163]
I have an invalid ingress that I tried to deploy. It reported success but the ingress did not change or show me the error.

Error should have been: `error: ingresses "web" could not be patched: cannot convert int64 to string`

What I saw:
```
[INFO][2017-09-08 19:28:45 +0000]	Deploying resources:
[INFO][2017-09-08 19:28:45 +0000]	- Ingress/web (timeout: 30s)
Successfully deployed in 8.8s: Ingress/web
```

**Comment by KnVerey** [comment]
That's very odd. Do you have the relevant part of the old/new specs I could use to try to reproduce this?

**Comment by dwradcliffe** [comment]
here's a sample:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/limit-rps: 30
  labels:
    name: web
    app: foobar
    environment: production
spec:
  rules:
  - host: foobar.example.com
    http:
      paths:
      - backend:
          serviceName: web
          servicePort: 80
 ```

Notice the `ingress.kubernetes.io/limit-rps` is an int where it should be a string
