### ISSUE TITLE
Unable to deploy service without selector

### ISSUE THREAD

**Issue by tandrup** [Shopify/kubernetes-deploy#167]
I have a service pointing to a Cassandra cluster outside my kubernetes cluster.

But when I try to deploy it using kubernetes-deploy I get this error:
```
[FATAL][2017-09-17 22:06:56 +0200]	No actions taken
/usr/local/lib/ruby/gems/2.4.0/gems/kubernetes-deploy-0.12.2/lib/kubernetes-deploy/kubernetes_resource/service.rb:53:in `selector': undefined method `map' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/kubernetes-deploy-0.12.2/lib/kubernetes-deploy/kubernetes_resource/service.rb:63:in `fetch_related_replica_count'
	from /usr/local/lib/ruby/gems/2.4.0/gems/kubernetes-deploy-0.12.2/lib/kubernetes-deploy/kubernetes_resource/service.rb:9:in `sync'
	from /usr/local/lib/ruby/gems/2.4.0/gems/kubernetes-deploy-0.12.2/lib/kubernetes-deploy/concurrency.rb:13:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/kubernetes-deploy-0.12.2/lib/kubernetes-deploy/concurrency.rb:13:in `block (2 levels) in split_across_threads'
```

Here's my service definition:

```
kind: Endpoints
apiVersion: v1
metadata:
  name: cassandra
  namespace: test
subsets:
  - addresses:
      - ip: 10.1.1.1
      - ip: 10.1.1.2
    ports:
      - name: cassandra
        port: 9042
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: test
spec:
  clusterIP: None
  ports:
    - name: cassandra
      port: 9042
```
