### ISSUE TITLE
Dockerized Deploy-Container

### ISSUE THREAD

**Issue by strowi** [Shopify/kubernetes-deploy#338]
Hi,

thx for this really nice little helper script. Took a lot of the pain out of migrating our teams to kubernetes-deployments.;)
Just wanted to let you know what i made out of it.
We were also migrating partly to gitlab the last couple of month, so i created a docker-container which would use the gitlab-provided variables by default, so deploying would be as easy as the folowing.
Also for ease of use we replace all variables with envsubst before kubernetes-shopify runs.

```

prod2:
  stage: deploy
  image: $IMAGE
  environment:
    name: master
    url: https://
  script:
    - deploy-k8-sys
  only:
    - master
  tags:
    - dind
```
-> https://github.com/strowi/deploy

regards,
Roman
