### ISSUE TITLE
Manifest validation error for RoleBindingList object

### ISSUE THREAD

**Issue by VincenzoDo** [Shopify/kubernetes-deploy#618]
# Bug report

I have the following manifest:
```
apiVersion: rbac.authorization.k8s.io/v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: myroleb-k8s
    namespace: test
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: myrole-k8s
  subjects:
  - kind: ServiceAccount
    name: sa-k8s
    namespace: test
kind: RoleBindingList
```
When I apply it with kubectl it works, but when I do the same with kubernetes-deploy I get a validation error

**Expected behavior:** 
Manifest applied.

**Actual behavior:** 
Validation error:
```
[INFO][2019-11-11 10:20:57 +0000]	[0;36;49m------------------------------------------Result: [0m[0;31;49mFAILURE[0m[0;36;49m-------------------------------------------[0m
[0;31;49m[FATAL][2019-11-11 10:20:57 +0000]	[0mFailed to render and parse template
[0;31;49m[FATAL][2019-11-11 10:20:57 +0000]	[0m
[0;31;49m[FATAL][2019-11-11 10:20:57 +0000]	[0m[0;31;49mInvalid template: 00prometheus-operator-roleSpecificNamespaces.yaml
[0;31;49m[FATAL][2019-11-11 10:20:57 +0000]	[0m[0m> Error message:
[0;31;49m[FATAL][2019-11-11 10:20:57 +0000]	[0m    Template is missing required field 'metadata.name'
[0;31;49m[FATAL][2019-11-11 10:20:57 +0000]	[0m> Template content:
[0;31;49m[FATAL][2019-11-11 10:20:57 +0000]	[0m    apiVersion: rbac.authorization.k8s.io/v1
[0;31;49m[FATAL][2019-11-11 10:20:57 +0000]	[0m    kind: RoleList
[0;31;49m[FATAL][2019-11-11 10:20:57 +0000]	[0m    metadata: {}
[0;31;49m[FATAL][2019-11-11 10:20:57 +0000]	[0m    <Template body suppressed because content sensitivity could not be determined.>
[0;31;49m[FATAL][2019-11-11 10:20:57 +0000]	[0m    
```

**Version(s) affected:**
I'm using the latest kubernetes-deploy release (v0.30.0) and kubectl v1.16.0 (and some earlier ones too).
